### ISSUE TITLE
공부할것!!

### ISSUE THREAD

**Issue by jdh1926** [Flying-mans/server#11]
## 공부
restful  [ ]
http 메소드 [ ]
동적쿼리 [ ]

주말동안 공부했으면 댓글로 진행 상황 적어주세요 🥇 

## 참고
[restful](https://fomaios.tistory.com/entry/Network-REST-API%EB%9E%80-feat-%EC%9B%90%EC%B9%99%EA%B3%BC-%EB%84%A4%EC%9D%B4%EB%B0%8D-%EA%B7%9C%EC%B9%99-What-is-a-REST-API)
[http 메소드](https://kyun2da.dev/CS/http-%EB%A9%94%EC%86%8C%EB%93%9C%EC%99%80-%EC%83%81%ED%83%9C%EC%BD%94%EB%93%9C/)
[동적쿼리](https://sinna94.tistory.com/entry/MyBatis-%EB%8F%99%EC%A0%81-%EC%BF%BC%EB%A6%AC-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

**Comment by sktkddn777** [comment]
restful [ O ]
http 메소드 [ O ]
동적쿼리 [ O ]

**Comment by choijinsoon** [comment]
restfull - O
정의, 사용 원칙, 네이밍 규칙

http 메소드 - O
정의, 종류, 속성, 상태코드

동작쿼리 - O
mybatis 동적 쿼리 조건 별 사용 방법

**Comment by choijinsoon** [comment]
궁금했던 점과 부족한 부분에 대해 알게 되었습니다

좋은 정보 감사합니다

**Comment by thislast** [comment]
restful - 완료

http 메소드 - 완료

동적쿼리 - 완료

**Comment by clwhale** [comment]
restful [ O ]
http 메소드 [ O ]
동적쿼리 [ O ]

**Comment by jdh1926** [comment]
restful [ O ]
http 메소드 [ O ]
동적쿼리 [ O ]
