### ISSUE TITLE
erd 에 role 추가

### ISSUE THREAD

**Issue by thislast** [Flying-mans/server#18]
스프링부트 권한에 대해 mysql role테이블을 추가하였습니다

role 테이블은 role_id와 name 컬럼으로 구성되어있습니다

member 테이블에 rold_id 추가하였습니다

1:1 형식의 role로 설정하였고

m:1 형식으로 바꿀 필요가 있는지 의견을 묻고싶습니다

**Comment by choijinsoon** [comment]
role 은 member 설정을 여러개 가능하고
member 는 role 설정을 한개만 가능하기 때문에
M:1 형식이 맞는 것 같습니다
